### ISSUE TITLE
Not able to run `sls invoke local`

### ISSUE THREAD

**Issue by mdanish0320** [sean9keenan/serverless-go-build#7]
sls build run successfully, it creates bin folder and inside that it created hello/main.
But when I run, `sls invoke local -f hello` to invoke the function locally, it says

```
$ sls invoke local -f hello
Serverless: Reassigning go paths to point to bin
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
START RequestId: b70a5bb1-e907-1b2b-c0bc-36dc127cdcb9 Version: $LATEST
END RequestId: b70a5bb1-e907-1b2b-c0bc-36dc127cdcb9
REPORT RequestId: b70a5bb1-e907-1b2b-c0bc-36dc127cdcb9  Init Duration: 57.26 ms Duration: 3.37 ms       Billed Duration: 4 ms   Memory Size: 1024 MB    Max Memory Used: 14 MB    

{"errorType":"exitError","errorMessage":"RequestId: a52cf12f-6450-1c6e-cc47-e12f58bf98a5 Error: fork/exec /var/task/hello/main.go: no such file or directory"}
```

This is the code, simple enough.
```
plugins:
  - serverless-go-build
package:
  individually: true

functions:
  hello:
    handler: hello/main.go
    events:
      - http:
          path: hello
          method: get
```
